# Generated by cpp11: do not edit by hand

start_mpi <- function() {
  invisible(.Call(`_dustmpi_start_mpi`))
}

get_mpi_size <- function() {
  .Call(`_dustmpi_get_mpi_size`)
}

get_mpi_rank <- function() {
  .Call(`_dustmpi_get_mpi_rank`)
}

end_mpi <- function() {
  invisible(.Call(`_dustmpi_end_mpi`))
}

get_mpi_wtime <- function() {
  .Call(`_dustmpi_get_mpi_wtime`)
}

simulate_model <- function(r_pars, initial_state, end_time, n_particles, r_rng_ptr, use_mpi) {
  .Call(`_dustmpi_simulate_model`, r_pars, initial_state, end_time, n_particles, r_rng_ptr, use_mpi)
}
