# Generated by cpp11: do not edit by hand

simulate_model <- function(r_pars, initial_state, end_time, n_particles, r_rng_ptr) {
  .Call(`_dustmpi_simulate_model`, r_pars, initial_state, end_time, n_particles, r_rng_ptr)
}
